name       : libffcall
version    : '2.4'
release    : 3
homepage   : https://www.gnu.org/software/libffcall/
source     :
    - https://ftp.gnu.org/gnu/libffcall/libffcall-2.4.tar.gz : 8ef69921dbdc06bc5bb90513622637a7b83a71f31f5ba377be9d8fd8f57912c2
license    : GPL-2.0-or-later
component  : programming.tools
summary    : GNU libffcall is a library which can be used to build foreign function call interfaces in embedded interpreters.
description: |
    It consists of two parts:
    - avcall: Calling C functions with variable arguments. Its include file is <avcall.h>.
    - callback: Closures with variable arguments as first-class C functions. Its include file is <callback.h>.
setup      : |
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install
check      : |
    %make check
