name       : libffcall
version    : 1.10
release    : 1
homepage   : http://www.gnu.org/software/libffcall/
source     :
    - http://www.haible.de/bruno/gnu/ffcall-1.10.tar.gz : 6f1b5b8fc84b2c0051637fb1e4e4f8b975f5f98bff8fe053c1992347baa4983d
license    : GPL-3.0
summary    : GNU Libffcall is a collection of four libraries which can be used to build foreign function call interfaces in embedded interpreters.
description: |
    GNU Libffcall is a collection of four libraries which can be used to build foreign function call interfaces in embedded interpreters: 
    Avcall, Vacall, Trampoline, and Callback.
setup      : |
    %configure --enable-shared --disable-static
build      : |
    %make -j1
install    : |
    install -m 00755 -d -D $installdir/usr/share
    install -m 00755 -d -D $installdir
    %make_install
